# ******************************************************************************
# User schema definition
# ******************************************************************************

type User {
  _id      : ID!      # actually the MongoDB ID
  username : String!
  password : String!
  firstName: String
  lastName : String
}

# ******************************************************************************
