# ******************************************************************************
# Role schema definition
# ******************************************************************************

type Role {
  _id      : ID!      # actually the MongoDB ID
  rolename : String!
}

# ******************************************************************************
